# Generated by Django 4.2.7 on 2023-12-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('BUG', 'Bug'), ('WORK', 'Work'), ('DONE', 'Done')], default='DONE', max_length=5),
        ),
    ]
