# Generated by Django 4.2.7 on 2023-12-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_issue_completed_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Task', 'Task'), ('Critical', 'Critical'), ('New Feature', 'Feature'), ('In Progress', 'Work'), ('Complete', 'Done')], default='Task', max_length=20),
        ),
    ]
